name: Conventional Commit Check

on:
  push:
    branches:
      - '**'

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Setup cocogitto
        uses: ./.github/actions/setup-cocogitto

      - name: Check version
        run: |
          cog changelog
          cog changelog -t monorepo_remote

      - name: Test bump version
        run: cog bump --auto  --dry-run || exit 1