name: Pull Request

on:
  pull_request:
    branches:
      - "**"

jobs:
  check_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup cocogitto
        uses: ./.github/actions/setup-cocogitto

      - name: Check version
        run: |
          cog changelog
          cog changelog -t monorepo_remote

      - name: Test bump version
        run: |
          cog bump --auto  --dry-run || exit 1
          git diff --exit-code || exit 1

