name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Perform release
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Setup cocogitto
        uses: ./.github/actions/setup-cocogitto

      - name: Check version
        run: |
          cog changelog
          cog changelog -t monorepo_remote

      - name: Test bump version
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          cog bump --auto  || exit 1
          git diff --exit-code || exit 1

          # output all CHANGELOG.md files
          find . -name CHANGELOG.md -exec cat {} \;

